.TH APINATE 1 "SEPTEMBER 2016"
.SH NAME
apinate \- a single-binary way to create config-driven, arbitrary HTTP API's
.SH SYNOPSIS
.B apinate
.I config-file
.B ]
.I file
.B ...
.SH DESCRIPTION
.B apinate
is a simple HTTP API that can be configured to run any back end
script or command and display the output in a variety of formats.
It runs as a single binary, and is driven by a single configuration
file.
.P
.B apinate
can output JSON, YAML or raw text and can be configured with
templates to output HTML.
.P
.B apinate
is the simplest and easiest way of spinning up a functional API\.
.SS "Caution"
Clearly 
.B apinate
has the potential to pose a significant security risk as it can be used to run arbitrary commands with the privileges assigned to the user it runs as. Do not, for example, link 
.B apinate
to a command such as rm, or even cat, unless you have taken appropriate precautions.
.
.P
.B apinate
should not be used with long (or continually) running commands, as the API endpoint will simply not return.
.SH OPTIONS
.B apinate
takes no options
.SH FILES
.B apinate
takes one configuration file, which may be in
.I toml, json
or
.I yaml
format.
.B apinate
will search for the files in the following order, and stop when one is found:
.P
.I ~/.apinate/apinate.toml, ~/.apinate/apinate.json, ~/.apinate/apinate.yaml
.P
.I /etc/apinate/apinate.toml, /etc/apinate/apinate.json, /etc/apinate/apinate.yaml
.P
.RS
- note that a per-user configuration file will take precedence over a system-wide config file
.RS
.SH EXAMPLES
Configuration is from resource (url) to command\. If additional parameters are to be passed to the command, the mapping should be passed a boolean called "params" set to true.
.P
The api can be directed to output json, html, yaml or raw text.
.P
address, port, params and template directives are optional for any endpoint and default to 0.0.0.0, 8080, false and plain.tmpl
.P
If HTML output is specified, you can create your own template files in 
.I ~/.apinate/templates
or
.I /usr/share/apinate/templates
and specify them in the mapping configuration (with the template directive)
.P
Configuration via
.B toml
:
.nf
address = "0\.0\.0\.0"
port = 8080
contenttype = "json"
[[mappings]]
  resource = "echo"
  command = "echo"
  params = true
[[mapping]]
  resource = "ping"
  command = "ping"
  params = true
[[mapping]]
  resource = hostname
  command = "hostname \-f"
  params = false
  template = "new\.tmpl"
.fi
.P
Configuration via
.B json
:
.nf
{
  "address": "0\.0\.0\.0"
  "port": 8080
  "contenttype": "html"
  "mappings": [
    {
      "resource": "echo",
      "command":  "echo",
      "params":   true
    },
    {
      "resource": "ping",
      "command":  "ping",
      "params":   true
    },
    {
      "resource": "hostname",
      "command":  "hostname \-f",
      "params":   false
    }
  ]
}
.fi
.P
Configuration via
.B yaml
:
.nf
address: 0\.0\.0\.0
port: 8080
contenttype: raw
mappings:
  \- resource: echo
    command:  echo
    params:   true
  \- resource: ping
    command:  ping
    params:   true
  \- resource: hostname
    command:  hostname \-f
    params:   false
.fi
.P
.SS Usage
The api may be accessed simply via HTTP requests:
.IP "\(bu" 4
http://hostname:8080/command
.
.IP "\(bu" 4
http://hostname:8080/command/parameters
.
.SS EXAMPLE 1
In order to report on the systems hostname, and the time taken to ping parameter\-driven locations, configured by json, outputting in xml:
.
.B "~/\.apinate\.json"
.P
.nf
{
  "contenttype": "html",
  "mappings": [
    {
      "resource": "system\-name",
      "command":  "hostname",
      "params":   false
    },
    {
      "resource": "ping\-time",
      "command":  "ping \-c 1 ",
      "params":   true
    }
  ]
}
.fi
.P
.B "output"
.nf
curl http://localhost:8080/system\-name
<html>
  <head></head>
  <body>
        <p>myhostname</p>
  </body>
</html>
curl http://localhost:8080/ping\-time/www\.google\.com
<html>
  <head></head>
  <body>
        <p>PING www\.google\.com (216\.58\.208\.132) 56(84) bytes of data\.</p>
        <p>64 bytes from lhr25s08\-in\-f132\.1e100\.net (216\.58\.208\.132): icmp_seq=1 ttl=57 time=18\.4 ms</p>
        <p></p>
        <p>\-\-\- www\.google\.com ping statistics \-\-\-</p>
        <p>1 packets transmitted, 1 received, 0% packet loss, time 0ms</p>
        <p>rtt min/avg/max/mdev = 18\.495/18\.495/18\.495/0\.000 ms</p>
  </body>
</html>
.fi

.SH AUTHOR
Philip Harries <Philip dot Harries at apinate dot io>
.
.SH OTHER DOCUMENTATION
See also:
.I https://github.com/PhilipHarries/apinate#apinate-
.
.SH LICENSE
.
MIT License
.P
Copyright (c) 2016 Philip Harries
.P
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
.P
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
.P
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
.
