contenttype = "json"
[[mappings]]
  resource = "echo"
  command = "echo"
  params = true
[[mappings]]
  resource = "cat"
  command = "cat"
  params = true
[[mappings]]
  resource = "ping"
  command = "ping -c 5 "
  params = true
[[mappings]]
  resource = "myscript"
  command = "/usr/local/bin/myscript"
  params = false
[[mappings.querykeys]]
  keyname = "name"
  default = "John Doe"
[[mappings.querykeys]]
  keyname = "age"
